### ISSUE TITLE
Incompatible with post tags?

### ISSUE THREAD

**Issue by tcw2682** [ArthurGareginyan/syntax-highlighter-for-postpage-html-editor#2]
Absolutely love this plugin - I've been using for the last couple of weeks. However I've just noticed that it appears to break the ability to add or remove 'tags' from posts? Not sure if anyone else is experiencing this problem or how knows how to fix? Fingers crossed.

Best wishes

**Comment by ArthurGareginyan** [comment]
I'm glad to hear that you love my plugin. Thanks for choosing it! :)

Thanks for reaching out and providing feedback of an issue you seeing.

I checked the ability to add or remove 'tags' from posts, and seems that it works properly. Please describe more what exactly you see. Can you show a screenshot of the problem?

Regards,
     Arthur
